#!/bin/bash

echo 'Enter new Ruby custom script filename:'
read name
if [ -e /script_files/$name ]
then
	echo 'That file already exists!'
else
	echo '#!/usr/bin/ruby
' > /script_files/$name
	chmod u+x /script_files/$name
	vim /script_files/$name
fi
